<?php
/**
 * Generated by the WordPress Meta Box Generator at http://goo.gl/8nwllb
 */
// Register Custom Post Type: Partner
if ( ! function_exists('custom_post_type_partner') ) {
function custom_post_type_partner() {
	$labels = array(
		'name'                  => _x( 'Partners', 'Post Type General Name', 'swiftbiz-lite' ),
		'singular_name'         => _x( 'Partner', 'Post Type Singular Name', 'swiftbiz-lite' ),
		'menu_name'             => __( 'Partners', 'swiftbiz-lite' ),
		'name_admin_bar'        => __( 'Partner', 'swiftbiz-lite' ),
		'archives'              => __( 'Partner Archives', 'swiftbiz-lite' ),
		'parent_item_colon'     => __( 'Parent Partner:', 'swiftbiz-lite' ),
		'all_items'             => __( 'All Partners', 'swiftbiz-lite' ),
		'add_new_item'          => __( 'Add New Partner', 'swiftbiz-lite' ),
		'add_new'               => __( 'Add New', 'swiftbiz-lite' ),
		'new_item'              => __( 'New Partner', 'swiftbiz-lite' ),
		'edit_item'             => __( 'Edit Partner', 'swiftbiz-lite' ),
		'update_item'           => __( 'Update Partner', 'swiftbiz-lite' ),
		'view_item'             => __( 'View Partner', 'swiftbiz-lite' ),
		'search_items'          => __( 'Search Partner', 'swiftbiz-lite' ),
		'not_found'             => __( 'Not found', 'swiftbiz-lite' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'swiftbiz-lite' ),
		'featured_image'        => __( 'Partner Logo', 'swiftbiz-lite' ),
		'set_featured_image'    => __( 'Set partner logo', 'swiftbiz-lite' ),
		'remove_featured_image' => __( 'Remove partner logo', 'swiftbiz-lite' ),
		'use_featured_image'    => __( 'Use as partner logo', 'swiftbiz-lite' ),
		'insert_into_item'      => __( 'Insert into partner', 'swiftbiz-lite' ),
		'uploaded_to_this_item' => __( 'Uploaded to this partner', 'swiftbiz-lite' ),
		'items_list'            => __( 'Partners list', 'swiftbiz-lite' ),
		'items_list_navigation' => __( 'Partners list navigation', 'swiftbiz-lite' ),
		'filter_items_list'     => __( 'Filter partners list', 'swiftbiz-lite' ),
	);
	$args = array(
		'label'                 => __( 'Partner', 'swiftbiz-lite' ),
		'description'           => __( 'Partner posts', 'swiftbiz-lite' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'thumbnail', ),
		'public'                => true,
		'has_archive'           => true,
		'menu_position'         => 0,
		'menu_icon'             => 'dashicons-groups',
		'can_export'            => true,
		'rewrite'               => array('slug' => 'partner'),
	);
	register_post_type( 'partner', $args );
}
add_action( 'init', 'custom_post_type_partner', 0 );
}

// Register Custom Post Type: Staff
if ( ! function_exists('custom_post_type_staff') ) {
function custom_post_type_staff() {
	$labels = array(
		'name'                  => _x( 'Staffs', 'Post Type General Name', 'swiftbiz-lite' ),
		'singular_name'         => _x( 'Staff', 'Post Type Singular Name', 'swiftbiz-lite' ),
		'menu_name'             => __( 'Staffs', 'swiftbiz-lite' ),
		'name_admin_bar'        => __( 'Staff', 'swiftbiz-lite' ),
		'archives'              => __( 'Staff Archives', 'swiftbiz-lite' ),
		'parent_item_colon'     => __( 'Parent Staff:', 'swiftbiz-lite' ),
		'all_items'             => __( 'All Staffs', 'swiftbiz-lite' ),
		'add_new_item'          => __( 'Add New Staff', 'swiftbiz-lite' ),
		'add_new'               => __( 'Add New', 'swiftbiz-lite' ),
		'new_item'              => __( 'New Staff', 'swiftbiz-lite' ),
		'edit_item'             => __( 'Edit Staff', 'swiftbiz-lite' ),
		'update_item'           => __( 'Update Staff', 'swiftbiz-lite' ),
		'view_item'             => __( 'View Staff', 'swiftbiz-lite' ),
		'search_items'          => __( 'Search Staff', 'swiftbiz-lite' ),
		'not_found'             => __( 'Not found', 'swiftbiz-lite' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'swiftbiz-lite' ),
		'featured_image'        => __( 'Staff photo', 'swiftbiz-lite' ),
		'set_featured_image'    => __( 'Set staff photo', 'swiftbiz-lite' ),
		'remove_featured_image' => __( 'Remove staff photo', 'swiftbiz-lite' ),
		'use_featured_image'    => __( 'Use as staff photo', 'swiftbiz-lite' ),
		'insert_into_item'      => __( 'Insert into staff', 'swiftbiz-lite' ),
		'uploaded_to_this_item' => __( 'Uploaded to this staff', 'swiftbiz-lite' ),
		'items_list'            => __( 'Staffs list', 'swiftbiz-lite' ),
		'items_list_navigation' => __( 'Staffs list navigation', 'swiftbiz-lite' ),
		'filter_items_list'     => __( 'Filter staffs list', 'swiftbiz-lite' ),
	);
	$args = array(
		'label'                 => __( 'Staff', 'swiftbiz-lite' ),
		'description'           => __( 'Staff pages', 'swiftbiz-lite' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'thumbnail', ),
		'public'                => true,
		'menu_position'         => 0,
		'menu_icon'             => 'dashicons-businessman',
		'can_export'            => true,
		'has_archive'           => true,
		'rewrite'               => array('slug' => 'staff'),

	);
	register_post_type( 'staff', $args );
}
add_action( 'init', 'custom_post_type_staff', 0 );
}

// Register Custom Taxonomy: Team
if ( ! function_exists( 'custom_taxonomy_team' ) ) {
function custom_taxonomy_team() {
	$labels = array(
		'name'                       => _x( 'Team', 'Taxonomy General Name', 'swiftbiz-lite' ),
		'singular_name'              => _x( 'Team', 'Taxonomy Singular Name', 'swiftbiz-lite' ),
		'menu_name'                  => __( 'Teams', 'swiftbiz-lite' ),
		'all_items'                  => __( 'All Teams', 'swiftbiz-lite' ),
		'parent_item'                => __( 'Parent Team', 'swiftbiz-lite' ),
		'parent_item_colon'          => __( 'Parent Team:', 'swiftbiz-lite' ),
		'new_item_name'              => __( 'New Team Name', 'swiftbiz-lite' ),
		'add_new_item'               => __( 'Add New Team', 'swiftbiz-lite' ),
		'edit_item'                  => __( 'Edit Team', 'swiftbiz-lite' ),
		'update_item'                => __( 'Update Team', 'swiftbiz-lite' ),
		'view_item'                  => __( 'View Team', 'swiftbiz-lite' ),
		'separate_items_with_commas' => __( 'Separate teams with commas', 'swiftbiz-lite' ),
		'add_or_remove_items'        => __( 'Add or remove teams', 'swiftbiz-lite' ),
		'choose_from_most_used'      => __( 'Choose from the most used', 'swiftbiz-lite' ),
		'popular_items'              => __( 'Popular Teams', 'swiftbiz-lite' ),
		'search_items'               => __( 'Search Teams', 'swiftbiz-lite' ),
		'not_found'                  => __( 'Not Found', 'swiftbiz-lite' ),
		'no_terms'                   => __( 'No teams', 'swiftbiz-lite' ),
		'items_list'                 => __( 'Teams list', 'swiftbiz-lite' ),
		'items_list_navigation'      => __( 'Teams list navigation', 'swiftbiz-lite' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => true,
		'query_var'                  => true,
		'rewrite'                    => true,
	);
	register_taxonomy( 'team', array( 'staff' ), $args );
}
add_action( 'init', 'custom_taxonomy_team', 0 );
}

// Register Custom Post Type: Property
if ( ! function_exists('custom_post_type_property') ) {
function custom_post_type_property() {
	$labels = array(
		'name'                  => _x( 'Properties', 'Post Type General Name', 'swiftbiz-lite' ),
		'singular_name'         => _x( 'Property', 'Post Type Singular Name', 'swiftbiz-lite' ),
		'menu_name'             => __( 'Properties', 'swiftbiz-lite' ),
		'name_admin_bar'        => __( 'Property', 'swiftbiz-lite' ),
		'archives'              => __( 'Property Archives', 'swiftbiz-lite' ),
		'parent_item_colon'     => __( 'Parent Property:', 'swiftbiz-lite' ),
		'all_items'             => __( 'All Properties', 'swiftbiz-lite' ),
		'add_new_item'          => __( 'Add New Property', 'swiftbiz-lite' ),
		'add_new'               => __( 'Add New', 'swiftbiz-lite' ),
		'new_item'              => __( 'New Property', 'swiftbiz-lite' ),
		'edit_item'             => __( 'Edit Property', 'swiftbiz-lite' ),
		'update_item'           => __( 'Update Property', 'swiftbiz-lite' ),
		'view_item'             => __( 'View Property', 'swiftbiz-lite' ),
		'search_items'          => __( 'Search Property', 'swiftbiz-lite' ),
		'not_found'             => __( 'Not found', 'swiftbiz-lite' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'swiftbiz-lite' ),
		'featured_image'        => __( 'Featured Image', 'swiftbiz-lite' ),
		'set_featured_image'    => __( 'Set featured image', 'swiftbiz-lite' ),
		'remove_featured_image' => __( 'Remove featured image', 'swiftbiz-lite' ),
		'use_featured_image'    => __( 'Use as featured image', 'swiftbiz-lite' ),
		'insert_into_item'      => __( 'Insert into Property', 'swiftbiz-lite' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Property', 'swiftbiz-lite' ),
		'items_list'            => __( 'Properties list', 'swiftbiz-lite' ),
		'items_list_navigation' => __( 'Properties list navigation', 'swiftbiz-lite' ),
		'filter_items_list'     => __( 'Filter Properties list', 'swiftbiz-lite' ),
	);
	$args = array(
		'label'                 => __( 'Property', 'swiftbiz-lite' ),
		'description'           => __( 'Properties custom post', 'swiftbiz-lite' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'excerpt', 'thumbnail', ),
		'public'                => true,
		'menu_position'         => 0,
		'menu_icon'             => 'dashicons-admin-multisite',
		'can_export'            => true,
		'has_archive'           => true,
		'rewrite'               => array('slug' => 'portfolio-type'),
	);
	register_post_type( 'property', $args );
}
add_action( 'init', 'custom_post_type_property', 0 );
}

// Register Custom Taxonomy: Property Type
if ( ! function_exists( 'custom_taxonomy_property_type' ) ) {
function custom_taxonomy_property_type() {
	$labels = array(
		'name'                       => _x( 'Property Types', 'Taxonomy General Name', 'swiftbiz-lite' ),
		'singular_name'              => _x( 'Property Type', 'Taxonomy Singular Name', 'swiftbiz-lite' ),
		'menu_name'                  => __( 'Property Type', 'swiftbiz-lite' ),
		'all_items'                  => __( 'All Property Types', 'swiftbiz-lite' ),
		'parent_item'                => __( 'Parent Property Type', 'swiftbiz-lite' ),
		'parent_item_colon'          => __( 'Parent Property Type:', 'swiftbiz-lite' ),
		'new_item_name'              => __( 'New Property Type Name', 'swiftbiz-lite' ),
		'add_new_item'               => __( 'Add New Property Type', 'swiftbiz-lite' ),
		'edit_item'                  => __( 'Edit Property Type', 'swiftbiz-lite' ),
		'update_item'                => __( 'Update Property Type', 'swiftbiz-lite' ),
		'view_item'                  => __( 'View Property Type', 'swiftbiz-lite' ),
		'separate_items_with_commas' => __( 'Separate Property types with commas', 'swiftbiz-lite' ),
		'add_or_remove_items'        => __( 'Add or remove Property types', 'swiftbiz-lite' ),
		'choose_from_most_used'      => __( 'Choose from the most used', 'swiftbiz-lite' ),
		'popular_items'              => __( 'Popular Property Types', 'swiftbiz-lite' ),
		'search_items'               => __( 'Search Property Types', 'swiftbiz-lite' ),
		'not_found'                  => __( 'Not Found', 'swiftbiz-lite' ),
		'no_terms'                   => __( 'No Property Types', 'swiftbiz-lite' ),
		'items_list'                 => __( 'Property types list', 'swiftbiz-lite' ),
		'items_list_navigation'      => __( 'Property types list navigation', 'swiftbiz-lite' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => true,
		'query_var'                  => true,
		'rewrite'                    => true,
	);
	register_taxonomy( 'property_type', array( 'property' ), $args );
}
add_action( 'init', 'custom_taxonomy_property_type', 0 );
}
?>
