<?php
/**
 * Generated by the WordPress Meta Box Generator at http://goo.gl/8nwllb
 */
 // Add Macland Options to Admin Menu.
 $pages = array(
   'maxwell_options'   => array(
     'page_title'    => __( 'Maxwell Options', 'swiftbiz-lite' ),
     'position'      => 4,
     'sections'      => array(
       'section-one'   => array(
         'title'         => __( 'Homepage Options', 'swiftbiz-lite' ),
         'fields'        => array(
           'header_title'    => array(
             'title'         => __( 'Header Picture Caption Title', 'swiftbiz-lite' ),
             'id'            => 'header_caption_title',
             'type'          => 'text',
             'placeholder'   => 'Put the title of the header picture here.',
           ),
           'header_content'    => array(
             'title'         => __( 'Header Picture Caption Contetn', 'swiftbiz-lite' ),
             'id'            => 'header_caption_contect',
             'type'          => 'textarea',
             'placeholder'   => 'Put the sub-contect of the header picture here.',
           ),
//           'act_pic'         => array(
//             'title'         => __( 'Activity Picture' ),
//             'id'            => 'activity_pic',
//             'type'          => 'media',
//             'value'         => '',
//             'placeholder'   => 'Click Upload to upload or choose picture for Activity',
//           ),
//           'act_date'        => array(
//             'title'         => __( 'Activity Date' ),
//             'id'            => 'activity_date',
//             'type'          => 'date',
//             'value'         => 'now',
//           ),
//           'h_slider_1'      => array(
//             'title'         => __( 'Home Slider Picrure 1' ),
//             'id'            => 'home_slider_1',
//             'type'          => 'media',
//             'value'         => '',
//             'placeholder'   => 'Click Upload to upload or choose the picture.',
//           ),
//           'h_sl_link_1'     => array(
//             'title'         => __( 'Home Slider Link 1' ),
//             'id'            => 'home_slider_link_1',
//             'type'          => 'url',
//             'placeholder'   => 'Link for Home Slider 1',
//           ),
//           'h_slider_2'      => array(
//             'title'         => __( 'Home Slider Picrure 2' ),
//             'id'            => 'home_slider_2',
//             'type'          => 'media',
//             'value'         => '',
//             'placeholder'   => 'Click Upload to upload or choose the picture.',
//           ),
//           'h_sl_link_2'     => array(
//             'title'         => __( 'Home Slider Link 2' ),
//             'id'            => 'home_slider_link_2',
//             'type'          => 'url',
//             'placeholder'   => 'Link for Home Slider 2',
//           ),
//           'h_slider_3'      => array(
//             'title'         => __( 'Home Slider Picrure 3' ),
//             'id'            => 'home_slider_3',
//             'type'          => 'media',
//             'value'         => '',
//             'placeholder'   => 'Click Upload to upload or choose the picture.',
//           ),
//           'h_sl_link_3'     => array(
//             'title'         => __( 'Home Slider Link 3' ),
//             'id'            => 'home_slider_link_3',
//             'type'          => 'url',
//             'placeholder'   => 'Link for Home Slider 3',
//           ),
         ),
       ),
       'section_two'   => array(
         'title'         => __( 'Website Options', 'swiftbiz-lite' ),
         'fields'        => array(
           'fluid_container' => array(
             'title'         => __( 'Use Fluid Containers', 'swiftbiz-lite' ),
             'id'            => 'fluid_container',
             'type'          => 'checkbox',
             'text'          => __( 'Check to use full-width fluid containers on pages.', 'swiftbiz-lite' ),
           ),
//           'disp_contact'    => array(
//             'title'         => __( 'Staff Contact Information' ),
//             'id'            => 'display_contact',
//             'type'          => 'checkbox',
//             'text'          => __( 'Display contact information in Team Page' ),
//           ),
//           'menu_search'    => array(
//             'title'         => __( 'Display Search on Main Menu' ),
//             'id'            => 'menu_search',
//             'type'          => 'checkbox',
//             'text'          => __( 'Display Search on Main Menu. If thrid party menu search plugin installed, uncheck this' ),
//           ),
           'comp_tel'        => array(
             'title'         => __( 'Company Telephone', 'swiftbiz-lite' ),
             'id'            => 'company_tel',
             'type'          => 'tel',
             'placeholder'   => '61-412-901-396',
           ),
//           'comp_fax'        => array(
//             'title'         => __( 'Company Fax' ),
//             'id'            => 'company_fax',
//             'type'          => 'tel',
//             'placeholder'   => '61-2-9736-2681',
//           ),
           'comp_address'    => array(
             'title'         => __( 'Company Address', 'swiftbiz-lite' ),
             'id'            => 'company_address',
             'type'          => 'text',
             'placeholder'   => '32/29-31 Paul St Bondi Junction NSW 2022',
           ),
//           'comp_s_weibo'    => array(
//             'title'         => __( 'Sina Weibo', 'swiftbiz-lite' ),
//             'id'            => 'company_sina_weibo',
//             'type'          => 'url',
//             'placeholder'   => __( 'Link of Sina Weibo', 'swiftbiz-lite' ),
//           ),
//           'comp_t_weibo'    => array(
//             'title'         => __( 'Tencent Weibo', 'swiftbiz-lite' ),
//             'id'            => 'company_tencent_weibo',
//             'type'          => 'url',
//             'placeholder'   => __( 'Link of Tencent Weibo', 'swiftbiz-lite' ),
//           ),
//           'comp_facebook'   => array(
//             'title'         => __( 'Facebook', 'swiftbiz-lite' ),
//             'id'            => 'company_facebook',
//             'type'          => 'url',
//             'placeholder'   => __( 'Link of Facebook', 'swiftbiz-lite' ),
//           ),
//           'comp_twitter'    => array(
//             'title'         => __( 'Twitter', 'swiftbiz-lite' ),
//             'id'            => 'company_twitter',
//             'type'          => 'url',
//             'placeholder'   => __( 'Link of Twitter', 'swiftbiz-lite' ),
//           ),
//           'comp_linkedin'     => array(
//             'title'         => __( 'Linkedin', 'swiftbiz-lite' ),
//             'id'            => 'company_linkedin',
//             'type'          => 'url',
//             'placeholder'   => __( 'Link of Linkedin', 'swiftbiz-lite' ),
//           ),
//           'comp_wechat'     => array(
//             'title'         => __( 'WeChat QrCode' ),
//             'id'            => 'company_wechat',
//             'type'          => 'media',
//             'value'         => '',
//             'placeholder'   => __( 'Click Upload to upload or choose the QrCode.', 'swiftbiz-lite' ),
//           ),
         ),
       ),
     ),
   ),
 );
 $option_page = new RationalOptionPages( $pages );
?>
